In [1]:
#import Numpy library
import numpy as np



In [2]:
# first Numpy array
first_numpy_array = np.array([1,2,3,4])


In [3]:
#print first array
print (first_numpy_array)


[1 2 3 4]


In [4]:
#array with zeroes
array_with_zeroes = np.zeros((3,3))
array_with_zeroes


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#array with empty
# caution this is a random number generator
array_with_empty = np.empty ((2,3))
array_with_empty



array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#array with arrange method
array_with_arrange = np.arange((12))
array_with_arrange



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
#linspace
np_linsplace = np.linspace(1,6,5)
print (np_linsplace)



[1.   2.25 3.5  4.75 6.  ]


In [9]:
# 2 D array

two_d_array = np.array([x for x in range (1,10)])
two_d_array
 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
two_d_array.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 3d array
three_D_array = np.array([x for x in range (1,13)])
three_D_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
three_D_array.reshape(3,2,2)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
# Conditional statements
x = np.array([i for i in range(10)])
x
 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.where(x%2==0,'Even', 'Odd')


array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [15]:
condlist = [x<5, x>5]
choicelist = [x**2, x**3]


In [16]:
np.select(condlist, choicelist, default=x)


array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

In [19]:
array_1d = np.array([ 1,  2,  3,  4,  5,  6])
array_2d = np.array([ 1,  2,  3], [4,  5,  6])
array_3d = np.array([ 1,  2,  3], [4,  5,  6], [7, 8, 9], [10, 11, 12])


TypeError: Field elements must be 2- or 3-tuples, got '4'