In [1]:
#import Numpy library
import numpy as np



In [3]:
# first Numpy array
first_numpy_array = np.array([1,2,3,4])


In [5]:
#print first array
print (first_numpy_array)


[1 2 3 4]


In [8]:
#array with zeroes
array_with_zeroes = np.zeros((3,3))
array_with_zeroes


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#array with empty
# caution this is a random number generator
array_with_empty = np.empty ((2,3))
array_with_empty



array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#array with arrange method
array_with_arrange = np.arange((12))
array_with_arrange



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
#linspace
np_linsplace = np.linspace(1,6,5)
print (np_linsplace)



SyntaxError: Missing parentheses in call to 'print'. Did you mean print(np_linsplace)? (2697344412.py, line 3)