In [1]:
#import Numpy library
import numpy as np



In [3]:
# first Numpy array
first_numpy_array = np.array([1,2,3,4])


In [5]:
#print first array
print (first_numpy_array)


[1 2 3 4]


In [8]:
#array with zeroes
array_with_zeroes = np.zeros((3,3))
array_with_zeroes


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#array with empty
# caution this is a random number generator
array_with_empty = np.empty ((2,3))
array_with_empty



array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#array with arrange method
array_with_arrange = np.arange((12))
array_with_arrange



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
#linspace
np_linsplace = np.linspace(1,6,5)
print (np_linsplace)



[1.   2.25 3.5  4.75 6.  ]


In [18]:
# 2 D array

two_d_array = np.array([x for x in range (1,10)])
two_d_array
 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
two_d_array.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 3d array
three_D_array = np.array([x for x in range (1,13)])
three_D_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
three_D_array.reshape(3,2,2)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
# can manipulate the array
three_D_array.reshape(3,2,2)
three_D_array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])